- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Install package
      package:
        name: "{{ morpheus['customOptions']['packageName'] }}"
        state: latest
      when: morpheus['customOptions']['packageName'] is defined